env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  'react/jsx-filename-extension': 'off',
  'max-classes-per-file': 'off',
  'import/extensions': 'off'
}
settings: {
  'import/resolver': {
    'node': {
      'extensions': ['.js', '.jsx', '.ts', '.tsx']
    }
  }
}
